### PR TITLE
Link to code of conduct solved.

### LINKED ISSUE #31: Link to code of conduct in Readme.md is broken

### PR DESCRIPTION
**Pull request by Rishav1707**
### This PR fixes the following issue:
fixes #31 

### Changes made:
- Added the working link of code_of_conduct.md in the readme file.
- Now in the readme.md file code of conduct link is working properly.

### CODE REVIEW

**Review by jonathanloos — CHANGES_REQUESTED** [review]
Hey @Rishav1707 thoughts on just making this an explicit reference to the `CODE_OF_CONDUCT.md` file in the repo instead of the full link. It would port better if the repo gets moved/changed

**Comment by Rishav1707** [comment]
> Hey @Rishav1707 thoughts on just making this an explicit reference to the `CODE_OF_CONDUCT.md` file in the repo instead of the full link. It would port better if the repo gets moved/changed

ok

**Comment by Rishav1707** [comment]
> Hey @Rishav1707 thoughts on just making this an explicit reference to the `CODE_OF_CONDUCT.md` file in the repo instead of the full link. It would port better if the repo gets moved/changed

Done @jonathanloos

**Review by jonathanloos — APPROVED** [review]
Thank you @Rishav1707, looks great.

**Pull request merged**
